#!/bin/sh

# makeself/hooks/build

set -euvx

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly project_dir="$(dirname "${here}")"

env | sort

# https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1
docker image build \
    --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --build-arg VCS_REF="$(git rev-parse HEAD)" \
    --tag "${IMAGE_NAME:-$(basename "${project_dir}")}" \
    "${project_dir}"
